# Generated by Django 4.1.7 on 2023-11-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_my', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='slug',
            field=models.SlugField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='shop_post',
            name='slug',
            field=models.SlugField(max_length=250, null=True),
        ),
    ]
